checkpoint_dir: "models/individual/egan/"
seed: 42  # random seed

dataset:
  seq_len: 300
  th_split: 30  # split keypoints sequence of an individual
  th_mask: 0.2

train:
  # actual_batch_size = batch_size * accumulate_grad_batches
  batch_size: 32
  accumulate_grad_batches: 128
  epochs: 30

inference:
  batch_size: 512
  anomaly_lambda: 0.5

model:
  G:
    d_z: 32
    d_model: 256
    d_ff: 1024
    n_heads: 8
    n_tr: 3
    dropout: 0.1
    activation: SELU
  D:
    d_z: 32
    d_model: 256
    d_ff: 1024
    d_out_feature: 32
    n_heads: 8
    n_tr: 6
    dropout: 0.1
    activation: SELU
  E:
    d_z: 32
    d_model: 256
    d_ff: 1024
    n_heads: 8
    n_tr: 6
    dropout: 0.1
    activation: SELU

optim:
  lr_g: 0.0004
  lr_d: 0.00005
  lr_e: 0.0004
  beta1: 0.9
  beta2: 0.999
