batch_size: 128
epochs: 30
seq_len: 300
th_split: 10  # split keypoints sequence of an individual

model:
  G:
    d_z: 32
    d_model: 64
    d_ff: 128
    n_heads: 8
    n_tre: 2
    dropout: 0.5
    activation: ReLU
  D:
    d_z: 32
    d_model: 64
    d_ff: 128
    n_heads: 8
    n_sttr: 1
    dropout: 0.5
    activation: SELU
  E:
    d_z: 32
    d_model: 64
    d_ff: 128
    n_heads: 8
    n_sttr: 2
    dropout: 0.5
    activation: SELU

optim:
  lr_g: 0.0001
  lr_d: 0.0001
  lr_e: 0.0001
  beta1: 0.9
  beta2: 0.999
