checkpoint_dir: "models/individual/egan/"
seed: 42  # random seed

dataset:
  seq_len: 300
  th_split: 10  # split keypoints sequence of an individual

train:
  batch_size: 128
  epochs: 200

inference:
  batch_size: 1024
  anomaly_lambda: 0.1

model:
  G:
    d_z: 256
    d_model: 128
    d_ff: 256
    n_heads: 8
    n_tre: 3
    dropout: 0.1
    activation: ReLU
  D:
    d_z: 256
    d_model: 128
    d_ff: 256
    n_heads: 8
    n_sttr: 2
    dropout: 0.1
    activation: SELU
  E:
    d_z: 256
    d_model: 128
    d_ff: 256
    n_heads: 8
    n_sttr: 3
    dropout: 0.1
    activation: SELU

optim:
  lr_g: 0.0001
  lr_d: 0.0001
  lr_e: 0.0001
  beta1: 0.9
  beta2: 0.999
