checkpoint_dir: "models/individual/gan/"
batch_size: 128
epochs: 200
seq_len: 300
th_split: 10  # split keypoints sequence of an individual
seed: 42  # random seed

model:
  G:
    d_z: 256
    d_model: 128
    d_ff: 256
    n_heads: 8
    n_tre: 2
    dropout: 0.1
    activation: ReLU
  D:
    d_model: 128
    d_ff: 256
    n_heads: 8
    n_sttr: 2
    dropout: 0.1
    activation: SELU

optim:
  lr_g: 0.0001
  lr_d: 0.0001
  beta1: 0.9
  beta2: 0.999
