batch_size: 32
epochs: 100
seq_len: 300
th_split: 10  # split keypoints sequence of an individual

model:
  G:
    d_z: 1024
    d_model: 256
    d_ff: 1024
    n_heads: 8
    n_tre: 2
    dropout: 0.1
    activation: ReLU
  D:
    d_model: 256
    d_ff: 1024
    d_output: 1
    n_heads: 8
    n_sttr: 2
    dropout: 0.1
    activation: SELU

optim:
  lr_g: 0.001
  lr_d: 0.004
  beta1: 0.9
  beta2: 0.999
