checkpoint_dir: "models/individual/ganomaly/"
seed: 42  # random seed

dataset:
  seq_len: 300
  th_split: 30  # split keypoints sequence of an individual
  th_mask: 0.2

train:
  # actual_batch_size = batch_size * accumulate_grad_batches
  batch_size: 64
  accumulate_grad_batches: 16
  epochs: 100

inference:
  batch_size: 768
  anomaly_lambda: 0.5

model:
  G:
    d_z: 50
    d_model: 256
    d_ff: 1024
    n_heads: 8
    n_tr_e: 5
    n_tr_d: 5
    dropout: 0.1
    activation: SELU
  D:
    d_model: 256
    d_ff: 1024
    d_out_feature: 64
    n_heads: 8
    n_tr: 5
    dropout: 0.1
    activation: SELU

loss:
  G:
    w_adv: 1
    w_con: 50
    w_lat: 1

optim:
  lr_g: 0.001
  lr_d: 0.0005
  beta1: 0.5
  beta2: 0.999
  lr_rate: 0.2
